#############################################################

#server_url=http://192.84.100.68:9103
#server_dynamic_url=http://192.84.100.96:9101
#login_url=http://192.84.100.68:3500
#api_creat_export_material=http://192.84.100.68:9999
#version=2.4.6
#system_name=MES_MMS
#schema_data = MES_MMS
#schema_core = MES_CORE

#############################################################

#server_url=http://192.84.100.96:9103
#server_dynamic_url=http://192.84.100.96:3800
#login_url=http://192.84.100.96:3500
#api_creat_export_material=http://192.84.100.96:9999
#version=2.4.6
#system_name=MES_MMS
#schema_data = MES_MMS
#schema_core = MES_CORE

#############################################################
# TODO: server api CheckSheet - 68
#server_url=http://192.84.100.68:9103
#server_dynamic_url=http://192.84.100.68:9101
#login_url=http://192.84.100.68:3500
#api_creat_export_material=http://192.84.100.68:9999
#version=2.4.6
#system_name=MES_MMS_MKVC
#schema_data = MES_MMS_MKVC
#schema_core = MES_CORE_MKVC
#screen_id=UPDATE_MOBIE_APP
#api_key=-
#vertical_lock=true



# TODO: server api WorkOrder
server_dynamic_url=http://192.86.0.225:9101/api/dynamics
#server_url=http://192.86.0.220:1521
server_url=http://192.86.0.225:9101
#login MKVC
#login_url=http://192.84.100.68:3500
#login MKHC
login_url=http://192.86.0.225:3800
api_creat_export_material=http://192.84.100.68:9999
version=2.4.7
system_name=MES_MMS_MKHC
schema_data=MES_DATA_MKHC
schema_mms=MES_MMS_MKHC
schema_core=MES_CORE_MKHC
schema_wms=MES_WMS_MKHC
screen_id=UPDATE_MOBIE_APP
api_key=""
vertical_lock=true
#server_url_mail=http://192.84.100.68:9103